routes/web.php
<?php

Auth::routes();
Route::get('/', 'PostController@index')->name('home');
Route::resource('posts', 'PostController')->except(['show', 'edit']);
Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('{slug}', 'PostController@show')->name('show');
    Route::get('{slug}/edit', 'PostController@edit')->name('edit');
});
Route::resource('users', 'UserController')->except(['show'])->middleware('admin');
Route::resource('tags', 'TagController')->except(['show'])->middleware('admin');;

app/Models/Post.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'body', 'user_id'
    ];

    /*
     * Generates an unique slug for post
     */
    public static function slugify($title)
    {
        $slug = str_slug($title, '-');
        if ($post = self::where('slug', $slug)->first())
            $slug .= '-' . ++$post->id;

        return $slug;
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getAuthorAttribute()
    {
        return optional($this->user)->name ?? 'Anonymous';
    }

    public function incrementViews()
    {
        $this->views++;
        return $this->save();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Post;
use App\Models\Tag;
use App\Repositories\PostsRepository;
use App\Repositories\Criteria\RelationAttribute;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected $postsRepository;

    public function __construct(PostsRepository $postsRepository)
    {
        $this->postsRepository = $postsRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @param  Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($tag = $request->input('tag'))
            $this->postsRepository->pushCriteria(new RelationAttribute('tags', 'name', $tag));

        $posts = $this->postsRepository->paginate(5);
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Post::class);
        $tags = Tag::all()->pluck('name', 'id');
        return view('posts.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  PostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $this->authorize('create', Post::class);
        $data = $request->only(['title', 'body']);
        $data['user_id'] = \Auth::user()->id;
        $data['slug'] = Post::slugify($data['title']);
        $this->postsRepository->createWithRelations($data, ['tags' => $request->tags]);

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $post = $this->postsRepository->findBy('slug', $slug);
        $post->incrementViews();
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $post = $this->postsRepository->findBy('slug', $slug);
        $this->authorize('update', $post);
        $tags = Tag::all()->pluck('name', 'id');

        return view('posts.edit', compact('post', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  PostRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $this->authorize('update', Post::findOrFail($id));
        $data = $request->only(['title', 'body']);
        $data['slug'] = Post::slugify($data['title']);
        $this->postsRepository->updateWithRelations($data, $id, ['tags' => $request->tags]);

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('delete', Post::findOrFail($id));
        $post = $this->postsRepository->find($id);
        $post->tags()->detach();
        $post->delete();
        return back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <h2>Create new post</h2>
                    <div class="panel-body">
                        {!! Form::open(['route' => ['posts.store'], 'method' => 'POST', 'class' => 'form-horizontal', 'id' => 'post-store']) !!}
                        <div class="form-group">
                            <label for="title" class="col-md-12 control-label">Title</label>

                            <div class="col-md-12">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required autofocus
                                       v-validate="'required|alpha_spaces|max:255'" @keyup="hideErrors"
                                       :class="{'is-invalid': errors.has('title') }">

                                <span class="text-danger">
                                    @if ($errors->has('title'))
                                        <strong v-show="displayErrors">{{ $errors->first('title') }}</strong>
                                    @endif
                                    <strong v-cloak v-show="errors.has('title')">@{{ errors.first('title') }}</strong>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="body" class="col-md-12 control-label">Body</label>

                            <div class="col-md-12">
                                <textarea id="body" form="post-store" type="text" name="body" required rows="15" class="form-control"
                                          v-validate="'required|max:65535'" @keyup="hideErrors"
                                          :class="{'is-invalid': errors.has('body') }">
                                    {{ old('body') }}
                                </textarea>

                                <span class="text-danger">
                                    @if ($errors->has('body'))
                                        <strong v-show="displayErrors">{{ $errors->first('body') }}</strong>
                                    @endif
                                    <strong v-cloak v-show="errors.has('body')">@{{ errors.first('body') }}</strong>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags" class="col-md-12 control-label">Tags</label>

                            <div class="col-md-12">
                                {!! Form::select('tags[]', $tags, null, [ 'class' => 'form-control select2', 'multiple' => 'multiple']) !!}

                                @if ($errors->has('tags'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('tags') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 col-md-offset-5">
                                <button type="submit" class="btn btn-outline-primary"
                                        @click.prevent="validateBeforeSubmit($event)">
                                    Create new post
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endpush
@push('footer_scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://unpkg.com/vee-validate@2.0.0-rc.7"></script>
    <script src="{{ asset('js/vue/validation.js') }}"></script>
    <script src="{{ asset('js/posts/selectTags.js') }}"></script>
@endpush

resources/views/posts/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <h2>Post edit</h2>
                    <div class="panel-body">
                        {!! Form::open(['route' => ['posts.update', $post->id], 'method' => 'PATCH', 'class' => 'form-horizontal', 'id' => 'post-store']) !!}
                        <div class="form-group">
                            <label for="title" class="col-md-12 control-label">Title</label>

                            <div class="col-md-12">
                                <input id="title" type="text" class="form-control" name="title" value="{{ $post->title }}" required autofocus
                                       v-validate="'required|alpha_spaces|max:255'" @keyup="hideErrors"
                                       :class="{'is-invalid': errors.has('title') }">

                                <span class="text-danger">
                                    @if ($errors->has('title'))
                                        <strong v-show="displayErrors">{{ $errors->first('title') }}</strong>
                                    @endif
                                    <strong v-cloak v-show="errors.has('title')">@{{ errors.first('title') }}</strong>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="body" class="col-md-12 control-label">Body</label>

                            <div class="col-md-12">
                                <textarea id="body" form="post-store" type="text" name="body" required rows="15" class="form-control"
                                          v-validate="'required|max:65535'" @keyup="hideErrors"
                                          :class="{'is-invalid': errors.has('body') }">
                                    {{ $post->body }}
                                </textarea>

                                <span class="text-danger">
                                    @if ($errors->has('body'))
                                        <strong v-show="displayErrors">{{ $errors->first('body') }}</strong>
                                    @endif
                                    <strong v-cloak v-show="errors.has('body')">@{{ errors.first('body') }}</strong>
                                </span>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                            <label for="tags" class="col-md-12 control-label">Tags</label>

                            <div class="col-md-12">
                                {!! Form::select('tags[]', $tags, $post->tags->pluck('id'), [ 'class' => 'form-control select2', 'multiple' => 'multiple']) !!}

                                @if ($errors->has('tags'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('tags') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 col-md-offset-5">
                                <button type="submit" class="btn btn-outline-primary" @click.prevent="validateBeforeSubmit($event)">
                                    Update post
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endpush
@push('footer_scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://unpkg.com/vee-validate@2.0.0-rc.7"></script>
    <script src="{{ asset('js/vue/validation.js') }}"></script>
    <script src="{{ asset('js/posts/selectTags.js') }}"></script>
@endpush

resources/views/posts/index.blade.php
@extends('layouts.main')
@section('content')
    @foreach($posts as $post)
        <!-- Blog Post -->
        <div class="card mb-4">
            <div class="card-body">
                <h3 class="card-title">{{ $post->title }}</h3>
                <p class="card-text">{{ str_limit($post->body, 100) }}</p>
                <a href="{{ route('posts.show', $post->slug) }}" class="btn btn-sm btn-outline-primary">Read More &rarr;</a>
                @can('update', $post)
                    <a href="{{ route('posts.edit', $post->slug) }}" class="btn btn-sm btn-outline-info">Edit</a>
                @endcan
                @can('delete', $post)
                    {!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE', 'class' => 'd-inline']) !!}
                    <button class='btn btn-sm btn-outline-danger'>Delete</button>
                    {!! Form::close() !!}
                @endcan
            </div>
            <div class="card-footer text-muted">
                Author: {{ $post->author }}
            </div>
            <div class="card-footer text-muted">
                Tags:
                @foreach($post->tags as $tag)
                    <a href="{{ route('posts.index', ['tag' => $tag->name]) }}">{{ $tag->name }}</a>
                @endforeach
            </div>
        </div>
    @endforeach
    {{ $posts->links() }}
@endsection

resources/views/posts/show.blade.php
@extends('layouts.main')
@section('content')
    <!-- Blog Post -->
    <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">{{ $post->title }}</h2>
            <p class="card-text">{{ $post->body }}</p>
            @can('update', $post)
                <a href="{{ route('posts.edit', $post->slug) }}" class="btn btn-sm btn-outline-primary">Edit post</a>
            @endcan
        </div>
        <div class="card-footer text-muted">
            Author: {{ $post->author }}
        </div>
        <div class="card-footer text-muted">
            Tags:
            @foreach($post->tags as $tag)
                <a href="{{ route('posts.index', ['tag' => $tag->name]) }}">{{ $tag->name }}</a>
            @endforeach
        </div>
    </div>
@endsection