routes/web.php
<?php

Auth::routes();
Route::get('/', 'PostController@index')->name('home');
Route::resource('posts', 'PostController')->except(['show', 'edit']);
Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('{slug}', 'PostController@show')->name('show');
    Route::get('{slug}/edit', 'PostController@edit')->name('edit');
});
Route::resource('users', 'UserController')->except(['show'])->middleware('admin');
Route::resource('tags', 'TagController')->except(['show'])->middleware('admin');;

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/site.css') }}" />
    @stack('css')
    <title>{{ config('app.name') }}</title>
</head>
<body>
<div id="app">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @guest
                        <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row mt-md-5">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-md-4">
                @yield('content')
            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4 mt-md-3">
                @can('create', \App\Models\Post::class)
                    <div class="card my-4">
                        <a href="{{ route('posts.create') }}" class="btn btn-info">Create new post</a>
                    </div>
                @endcan

                @if(optional(Auth::user())->is_admin)
                    <div class="card my-4">
                        <h5 class="card-header">Admin Zone</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <a href="{{ route('users.index') }}">Users</a>
                                        </li>
                                        <li>
                                            <a href="{{ route('tags.index') }}">Tags</a>
                                        </li>
                                        <li>
                                            <a href="{{ route('posts.index') }}">Posts</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
            @endif

            <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Top Tags</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <ul class="list-unstyled mb-0">
                                    @foreach($topTags as $tag)
                                        <li>
                                            <a href="{{ route('posts.index', ['tag' => $tag->name]) }}">{{ $tag->name }}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>
@stack('footer_scripts')
</body>
</html>